question_bank = {
    "The capital of Australia is Canberra.": "True",
    "The Nobel Peace Prize is awarded in Oslo, Norway.": "True",
    "The chemical symbol of Silver is Ag.": "True",
    "The largest desert in the world is the Sahara Desert.": "False",
    "Antarctica is the largest desert on Earth.": "True",
    "Venus is the hottest planet in the Solar System.": "True",
    "The Great Barrier Reef is located in Australia.": "True",
    "The Panama Canal connects the Atlantic and Pacific Oceans.": "True",
    "The Suez Canal connects the Mediterranean Sea and the Red Sea.": "True",
    "Julius Caesar was the first Roman Emperor.": "False",
    "Augustus was the first Roman Emperor.": "True",
    "An octopus has three hearts.": "True",
    "The human body has 206 bones in adulthood.": "True",
    "The speed of light is approximately 300,000 km/s.": "True",
    "The currency of Switzerland is the Euro.": "False",
    "The currency of Switzerland is the Swiss Franc.": "True",
    "The longest river in the world is the Nile.": "False",
    "The Amazon River carries the largest volume of water in the world.": "True",
    "The Statue of Liberty was a gift from France to the USA.": "True",
    "The Eiffel Tower was originally intended to be permanent.": "False",
    "Shakespeare wrote 'Macbeth'.": "True",
    "The Taj Mahal was built by Akbar.": "False",
    "The Taj Mahal was built by Shah Jahan.": "True",
    "Mount Kilimanjaro is located in Tanzania.": "True",
    "The largest ocean on Earth is the Pacific Ocean.": "True",
    "Mercury is the smallest planet in the Solar System.": "True",
    "Saturn is the only planet with rings.": "False",
    "The headquarters of the United Nations is in New York City.": "True",
    "The International Space Station orbits the Earth.": "True",
    "The SI unit of force is the Newton.": "True",
    "Albert Einstein received the Nobel Prize for the Theory of Relativity.": "False",
    "Albert Einstein won the Nobel Prize for the Photoelectric Effect.": "True",
    "The human heart has four chambers.": "True",
    "A group of lions is called a pride.": "True",
    "A group of crows is called a murder.": "True",
    "Blue whales are the largest animals to have ever lived.": "True",
    "The human brain contains no blood vessels.": "False",
    "The chemical formula of table salt is NaCl.": "True",
    "DNA stands for Deoxyribonucleic Acid.": "True",
    "The Great Wall of China is visible from the Moon with the naked eye.": "False",
    "The first man to walk on the Moon was Neil Armstrong.": "True",
    "India became independent in 1947.": "True",
    "The Indian Constitution came into force on 26 January 1950.": "True",
    "The capital of Canada is Toronto.": "False",
    "The capital of Canada is Ottawa.": "True",
    "Bhutan is the only country with Gross National Happiness as an official development philosophy.": "True",
    "The currency of Japan is the Yen.": "True",
    "The binary number system uses only two digits: 0 and 1.": "True",
    "HTML is a programming language.": "False",
    "The CPU is often called the brain of the computer.": "True",
    "The first FIFA World Cup was held in Uruguay.": "True",
    "The Olympic Games are held every five years.": "False",
    "Michael Phelps has won more Olympic gold medals than any other athlete.": "True",
    "Sachin Tendulkar scored 100 international centuries.": "True",
    "The Wimbledon tennis tournament is played on clay courts.": "False",
    "The Tour de France is a cycling competition.": "True",
    "The capital of South Africa is Cape Town only.": "False",
    "South Africa has three capital cities.": "True",
    "Russia is the largest country in the world by area.": "True",
    "Greenland is an independent country.": "False",
    "The Dead Sea lies below sea level.": "True",
    "Lake Baikal is the world's deepest freshwater lake.": "True",
    "The Andes are the longest continental mountain range in the world.": "True",
    "Indonesia consists of more than 17,000 islands.": "True",
    "Iceland lies on both the North American and Eurasian tectonic plates.": "True",
    "The Richter scale measures earthquake magnitude.": "True",
    "A tsunami is usually caused by underwater earthquakes.": "True",
    "Sound travels faster in water than in air.": "True",
    "Diamond is made primarily of carbon.": "True",
    "Graphite and diamond are allotropes of carbon.": "True",
    "Vitamin D is mainly produced in the skin through sunlight exposure.": "True",
    "Insulin is produced by the pancreas.": "True",
    "Red blood cells contain hemoglobin.": "True",
    "Viruses can reproduce without a host cell.": "False",
    "The human eye naturally has a blind spot.": "True",
    "The smallest unit of life is the cell.": "True",
    "Electrons are larger than protons.": "False",
    "Platinum is more valuable than silver in general.": "True",
    "The boiling point of pure water at sea level is 100°C.": "True",
    "Lightning is hotter than the surface of the Sun.": "True",
    "The first artificial satellite was Sputnik 1.": "True",
    "Mars has two natural moons.": "True",
    "Jupiter has the most confirmed moons of any planet.": "True",
    "The Milky Way is a galaxy.": "True",
    "The Sun revolves around the Earth.": "False",
    "A light-year is a unit of distance.": "True",
    "The Hubble Space Telescope is named after Edwin Hubble.": "True",
    "Python was created by Guido van Rossum.": "True",
    "Linux is an open-source operating system.": "True",
    "The first electronic general-purpose computer was ENIAC.": "True",
    "A byte consists of 8 bits.": "True",
    "The Internet and the World Wide Web are the same thing.": "False",
    "USB stands for Universal Serial Bus.": "True",
    "The first email was sent before the World Wide Web was invented.": "True",
    "The Reserve Bank of India issues Indian currency notes (except the ₹1 note).": "True",
    "The Indian Parliament consists of the Lok Sabha and Rajya Sabha.": "True",
    "Article 370 of the Indian Constitution originally granted special status to Jammu and Kashmir.": "True",
    "The Constitution of India is the longest written national constitution in the world.": "True",
    "The United Nations was founded in 1945.": "True",
    "The World Health Organization (WHO) is a specialized agency of the United Nations.": "True"
}